version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - todo-postgres-data:/var/lib/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: atm
  atm-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 81:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/atm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123

volumes:
  todo-postgres-data: