spring:
  datasource:
    url: jdbc:postgresql://db:5432/atm
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      dll-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true


